
title: My CV
url: 'https://lentzi90.github.io/'
baseurl: '/CV' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Lennart Jern
tagline: Software Engineer, Master of Mathematics, Teacher, Nerd
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: lennart.jern@gmail.com
#phone: 012 345 6789
website: https://lentzi90.github.io/
personal_website: https://jern.me
linkedin: lennart-jern-426335131
github: lentzi90
twitter: '@lennartjern'
